//
// Created by maikeu on 17/09/2019.
//

#ifndef TOMADA_SMART_CONDO_PRIORITIES_H
#define TOMADA_SMART_CONDO_PRIORITIES_H

#define MAX_PRIORITY configMAX_PRIORITIES
#define HIGHEST_PRIORITY (6)
#define HIGH_PRIORITY (5)
#define MEDIUM_PRIORITY (4)
#define LOW_PRIORITY (3)
#endif //TOMADA_SMART_CONDO_PRIORITIES_H
